### PR TITLE
add a select_all (Strg+a) option to the select_multiple in utils.cutie

### PR DESCRIPTION
**Pull request by tobiasfunke1**
I have added the possibility to select all courses at once with Strg+a. I joined a lot of courses and my screen is not big enough, so for me it is a real nice feature ;)

EDIT: I created a new request, because i have multiple branches for different features/patches now. This PR contains just the select_all part...

just this commit: c3d9591cd66ba165621c26409a81a6a1ef63386e

### CODE REVIEW

**Comment by C0D3D3V** [comment]
That is a very nice feature :) 
Thank you very much. I will merge it tomorrow evening.

**Comment by tobiasfunke1** [comment]
nice!

**Comment by C0D3D3V** [comment]
Sorry for the long delay. I hope I have now more time for the project. Thank you very much for your contributions

**Comment by C0D3D3V** [comment]
Thank you very much :)

**Pull request merged**
