### PR TITLE
WIP / please review

### PR DESCRIPTION
**Pull request by eMPee584**
Please have a look at these. Got stuck on the last one.. otherwise (from a quick glance) tool seems awesome.. 👌😏
missing an option to download bestandsfiles if skipped the initial sync..

### CODE REVIEW

**Comment by C0D3D3V** [comment]
`print os.stat(filename)`
is python 2 syntax. In Python 3 there are no more free standing arguments as far as I know. That means you have to bracket the argument. Like this:
`print(os.stat(filename))`

There is no benefit in renaming the main.py. It is called main.py for historical reasons, a renaming would only result in old users having to change their habits. New users won't notice if they install the downloader with pip, because then the script will be installed as moodle-dl. 

But I like to be persuaded with a good argument, but then please adapt the setup.py as well.

In general you should avoid unnecessary print instructions for debugging. For vscode (visual studio code) i have created a configuration (which has to be adjusted after renaming) with which you can debug the downloader. Just open the project in vscode and press F5. By pressing on the line numbers you can add breakpoints, if the program stops you can hkver over variable names to learn more about them or use the debug console.

**Comment by C0D3D3V** [comment]
There is no initial sync. After each call of moodle-dl an offline created SQlite DB is compared with the data returned by the API, all differences are downloaded. So you can't miss any file. If I get you wrong, please open an issue.

**Comment by C0D3D3V** [comment]
By the way, I like the timestamp adjustment very much, I had the idea myself once, but never tried to implement it.  By the way, if Last-Modified is not available in the header, it is also in the file itself. Take a look at `self.file` while debugging.

**Comment by C0D3D3V** [comment]
For inspiration... this is how youtube-dl does it: https://github.com/ytdl-org/youtube-dl/blob/c5764b3f89b66e0148a186490f522ae7c259a55e/youtube_dl/downloader/http.py#L335

**Comment by C0D3D3V** [comment]
The part with setup.py is wrong, I had it wrong in my head. We can rename the main.py, old users can easily adapt

**Comment by C0D3D3V** [comment]
do you want to finish your work, or should I implement it for you?

**Comment by eMPee584** [comment]
Hey Daniel.. I am quite busy with our https://schulstick.org and finishing https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456 so I'll gladly take your offer :+1: :sweat_smile:

**Pull request closed without merging**
